In [ ]:
!pip install --upgrade --force-reinstall numpy pandas mendeleev pymatgen

Collecting numpy
  Downloading numpy-2.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.1 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 5.2 MB/s eta 0:00:00
Collecting mendeleev
  Downloading mendeleev-1.0.0-py3-none-any.whl.metadata (21 kB)
Collecting pymatgen
  Downloading pymatgen-2025.4.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting Pygments<3.0.0,>=2.11.2 (from mendeleev)
  Downloading pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)
Collecting SQLAlchemy>=1.4.0 (from mendeleev)
  Downloading sqlalchemy-2.0.40-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting colorama<0.5.0,>=0.4.6 (from mendeleev)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting deprecated<2.0.0,>=1.2.14 (from mendeleev)
  Downloading Deprecated-1.2.18-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting numpy
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.3 MB/s eta 0:00:00
Collecting pydantic<3.0.0,>=2.9.2 (from mendeleev)
  Downloading pydantic-2.11.3-py3-none-any.whl.metadata (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.2/65.2 kB 5.5 MB/s eta 0:00:00
Collecting pyfiglet<0.9,>=0.8.post1 (from mendeleev)
  Downloading pyfiglet-0.8.post1-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting joblib>=1 (from pymatgen)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting matplotlib>=3.8 (from pymatgen)
  Downloading matplotlib-3.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting monty>=2025.1.9 (from pymatgen)
  Downloading monty-2025.3.3-py3-none-any.whl.metadata (3.6 kB)
Collecting networkx>=2.7 (from pymatgen)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting palettable>=3.3.3 (from pymatgen)
  Downloading palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting plotly>=5.0.0 (from pymatgen)
  Downloading plotly-6.0.1-py3-none-any.whl.metadata (6.7 kB)
Collecting pybtex>=0.24.0 (from pymatgen)
  Downloading pybtex-0.24.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting requests>=2.32 (from pymatgen)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting ruamel.yaml>=0.17.0 (from pymatgen)
  Downloading ruamel.yaml-0.18.10-py3-none-any.whl.metadata (23 kB)
Collecting scipy>=1.13.0 (from pymatgen)
  Downloading scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 5.0 MB/s eta 0:00:00
Collecting spglib>=2.5 (from pymatgen)
  Downloading spglib-2.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting sympy>=1.3 (from pymatgen)
  Downloading sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting tabulate>=0.9 (from pymatgen)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting tqdm>=4.60 (from pymatgen)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 5.7 MB/s eta 0:00:00
Collecting uncertainties>=3.1.4 (from pymatgen)
  Downloading uncertainties-3.2.2-py3-none-any.whl.metadata (6.9 kB)
Collecting wrapt<2,>=1.10 (from deprecated<2.0.0,>=1.2.14->mendeleev)
  Downloading wrapt-1.17.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.8->pymatgen)
  Downloading contourpy-1.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib>=3.8->pymatgen)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.8->pymatgen)
  Downloading fonttools-4.57.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.5/102.5 kB 9.9 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.8->pymatgen)
  Downloading kiwisolver-1.4.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.2 kB)
Collecting packaging>=20.0 (from matplotlib>=3.8->pymatgen)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pillow>=8 (from matplotlib>=3.8->pymatgen)
  Downloading pillow-11.2.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Collecting pyparsing>=2.3.1 (from matplotlib>=3.8->pymatgen)
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Collecting narwhals>=1.15.1 (from plotly>=5.0.0->pymatgen)
  Downloading narwhals-1.35.0-py3-none-any.whl.metadata (9.2 kB)
Collecting PyYAML>=3.01 (from pybtex>=0.24.0->pymatgen)
  Downloading PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting latexcodec>=1.0.4 (from pybtex>=0.24.0->pymatgen)
  Downloading latexcodec-3.0.0-py3-none-any.whl.metadata (4.9 kB)
Collecting six (from pybtex>=0.24.0->pymatgen)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.9.2->mendeleev)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.1 (from pydantic<3.0.0,>=2.9.2->mendeleev)
  Downloading pydantic_core-2.33.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting typing-extensions>=4.12.2 (from pydantic<3.0.0,>=2.9.2->mendeleev)
  Downloading typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
Collecting typing-inspection>=0.4.0 (from pydantic<3.0.0,>=2.9.2->mendeleev)
  Downloading typing_inspection-0.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.32->pymatgen)
  Downloading charset_normalizer-3.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting idna<4,>=2.5 (from requests>=2.32->pymatgen)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.32->pymatgen)
  Downloading urllib3-2.4.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests>=2.32->pymatgen)
  Downloading certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.17.0->pymatgen)
  Downloading ruamel.yaml.clib-0.2.12-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Collecting greenlet>=1 (from SQLAlchemy>=1.4.0->mendeleev)
  Downloading greenlet-3.1.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.3->pymatgen)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 109.0 MB/s eta 0:00:00
Downloading mendeleev-1.0.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 68.2 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 99.2 MB/s eta 0:00:00
Downloading pymatgen-2025.4.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 108.1 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading Deprecated-1.2.18-py2.py3-none-any.whl (10.0 kB)
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 26.8 MB/s eta 0:00:00
Downloading matplotlib-3.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 112.1 MB/s eta 0:00:00
Downloading monty-2025.3.3-py3-none-any.whl (51 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.9/51.9 kB 4.9 MB/s eta 0:00:00
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 80.1 MB/s eta 0:00:00
Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 27.9 MB/s eta 0:00:00
Downloading plotly-6.0.1-py3-none-any.whl (14.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 100.7 MB/s eta 0:00:00
Downloading pybtex-0.24.0-py2.py3-none-any.whl (561 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.4/561.4 kB 40.4 MB/s eta 0:00:00
Downloading pydantic-2.11.3-py3-none-any.whl (443 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.6/443.6 kB 34.8 MB/s eta 0:00:00
Downloading pydantic_core-2.33.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 81.3 MB/s eta 0:00:00
Downloading pyfiglet-0.8.post1-py2.py3-none-any.whl (865 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.8/865.8 kB 51.9 MB/s eta 0:00:00
Downloading pygments-2.19.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 66.8 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 20.8 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 38.9 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 5.9 MB/s eta 0:00:00
Downloading ruamel.yaml-0.18.10-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.7/117.7 kB 11.3 MB/s eta 0:00:00
Downloading scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.6/37.6 MB 13.7 MB/s eta 0:00:00
Downloading spglib-2.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (809 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 809.0/809.0 kB 50.7 MB/s eta 0:00:00
Downloading sqlalchemy-2.0.40-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 91.3 MB/s eta 0:00:00
Downloading sympy-1.13.3-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 115.3 MB/s eta 0:00:00
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 6.5 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 28.8 MB/s eta 0:00:00
Downloading uncertainties-3.2.2-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 5.9 MB/s eta 0:00:00
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading certifi-2025.1.31-py3-none-any.whl (166 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.4/166.4 kB 17.0 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.9/143.9 kB 14.8 MB/s eta 0:00:00
Downloading contourpy-1.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (326 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 326.2/326.2 kB 29.5 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.57.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 97.1 MB/s eta 0:00:00
Downloading greenlet-3.1.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (602 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 602.4/602.4 kB 46.3 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 6.7 MB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 66.7 MB/s eta 0:00:00
Downloading latexcodec-3.0.0-py3-none-any.whl (18 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 40.2 MB/s eta 0:00:00
Downloading narwhals-1.35.0-py3-none-any.whl (325 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.7/325.7 kB 30.1 MB/s eta 0:00:00
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 6.6 MB/s eta 0:00:00
Downloading pillow-11.2.1-cp311-cp311-manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 105.1 MB/s eta 0:00:00
Downloading pyparsing-3.2.3-py3-none-any.whl (111 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.1/111.1 kB 11.5 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (762 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 763.0/763.0 kB 53.5 MB/s eta 0:00:00
Downloading ruamel.yaml.clib-0.2.12-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (739 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.1/739.1 kB 53.4 MB/s eta 0:00:00
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 4.3 MB/s eta 0:00:00
Downloading typing_inspection-0.4.0-py3-none-any.whl (14 kB)
Downloading urllib3-2.4.0-py3-none-any.whl (128 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.7/128.7 kB 12.8 MB/s eta 0:00:00
Downloading wrapt-1.17.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (83 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.2/83.2 kB 9.6 MB/s eta 0:00:00
Installing collected packages: pytz, pyfiglet, mpmath, wrapt, urllib3, uncertainties, tzdata, typing-extensions, tqdm, tabulate, sympy, six, ruamel.yaml.clib, PyYAML, pyparsing, Pygments, pillow, palettable, packaging, numpy, networkx, narwhals, latexcodec, kiwisolver, joblib, idna, greenlet, fonttools, cycler, colorama, charset-normalizer, certifi, annotated-types, typing-inspection, SQLAlchemy, spglib, scipy, ruamel.yaml, requests, python-dateutil, pydantic-core, pybtex, plotly, deprecated, contourpy, pydantic, pandas, monty, matplotlib, pymatgen, mendeleev
  Attempting uninstall: pytz
    Found existing installation: pytz 2025.2
    Uninstalling pytz-2025.2:
      Successfully uninstalled pytz-2025.2
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.2
    Uninstalling wrapt-1.17.2:
      Successfully uninstalled wrapt-1.17.2
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.3.0
    Uninstalling urllib3-2.3.0:
      Successfully uninstalled urllib3-2.3.0
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2025.2
    Uninstalling tzdata-2025.2:
      Successfully uninstalled tzdata-2025.2
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.13.1
    Uninstalling typing_extensions-4.13.1:
      Successfully uninstalled typing_extensions-4.13.1
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
  Attempting uninstall: tabulate
    Found existing installation: tabulate 0.9.0
    Uninstalling tabulate-0.9.0:
      Successfully uninstalled tabulate-0.9.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.1
    Uninstalling sympy-1.13.1:
      Successfully uninstalled sympy-1.13.1
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.2
    Uninstalling PyYAML-6.0.2:
      Successfully uninstalled PyYAML-6.0.2
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.2.3
    Uninstalling pyparsing-3.2.3:
      Successfully uninstalled pyparsing-3.2.3
  Attempting uninstall: Pygments
    Found existing installation: Pygments 2.18.0
    Uninstalling Pygments-2.18.0:
      Successfully uninstalled Pygments-2.18.0
  Attempting uninstall: pillow
    Found existing installation: pillow 11.1.0
    Uninstalling pillow-11.1.0:
      Successfully uninstalled pillow-11.1.0
  Attempting uninstall: packaging
    Found existing installation: packaging 24.2
    Uninstalling packaging-24.2:
      Successfully uninstalled packaging-24.2
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: networkx
    Found existing installation: networkx 3.4.2
    Uninstalling networkx-3.4.2:
      Successfully uninstalled networkx-3.4.2
  Attempting uninstall: narwhals
    Found existing installation: narwhals 1.34.1
    Uninstalling narwhals-1.34.1:
      Successfully uninstalled narwhals-1.34.1
  Attempting uninstall: kiwisolver
    Found existing installation: kiwisolver 1.4.8
    Uninstalling kiwisolver-1.4.8:
      Successfully uninstalled kiwisolver-1.4.8
  Attempting uninstall: joblib
    Found existing installation: joblib 1.4.2
    Uninstalling joblib-1.4.2:
      Successfully uninstalled joblib-1.4.2
  Attempting uninstall: idna
    Found existing installation: idna 3.10
    Uninstalling idna-3.10:
      Successfully uninstalled idna-3.10
  Attempting uninstall: greenlet
    Found existing installation: greenlet 3.1.1
    Uninstalling greenlet-3.1.1:
      Successfully uninstalled greenlet-3.1.1
  Attempting uninstall: fonttools
    Found existing installation: fonttools 4.57.0
    Uninstalling fonttools-4.57.0:
      Successfully uninstalled fonttools-4.57.0
  Attempting uninstall: cycler
    Found existing installation: cycler 0.12.1
    Uninstalling cycler-0.12.1:
      Successfully uninstalled cycler-0.12.1
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.4.1
    Uninstalling charset-normalizer-3.4.1:
      Successfully uninstalled charset-normalizer-3.4.1
  Attempting uninstall: certifi
    Found existing installation: certifi 2025.1.31
    Uninstalling certifi-2025.1.31:
      Successfully uninstalled certifi-2025.1.31
  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.7.0
    Uninstalling annotated-types-0.7.0:
      Successfully uninstalled annotated-types-0.7.0
  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.0
    Uninstalling typing-inspection-0.4.0:
      Successfully uninstalled typing-inspection-0.4.0
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 2.0.40
    Uninstalling SQLAlchemy-2.0.40:
      Successfully uninstalled SQLAlchemy-2.0.40
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1
  Attempting uninstall: requests
    Found existing installation: requests 2.32.3
    Uninstalling requests-2.32.3:
      Successfully uninstalled requests-2.32.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.2

**:IMPORTING REQIURED MODULES**

In [ ]:
!pip install CBFV

Collecting CBFV
  Downloading CBFV-1.1.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from CBFV) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from CBFV) (2.2.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from CBFV) (4.67.1)
Requirement already satisfied: pytest in /usr/local/lib/python3.11/dist-packages (from CBFV) (8.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->CBFV) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->CBFV) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->CBFV) (2025.2)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.11/dist-packages (from pytest->CBFV) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from pytest->CBFV) (24.2)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.11/dist-packages (from pytest->CBFV) (1.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->CBFV) (1.17.0)
Downloading CBFV-1.1.0-py3-none-any.whl (539 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 539.2/539.2 kB 8.7 MB/s eta 0:00:00
Installing collected packages: CBFV
Successfully installed CBFV-1.1.0

In [ ]:
import pandas as pd
import numpy as np
from pymatgen.core import Composition, Element
from mendeleev import element
from CBFV.composition import generate_features

***READING THE DATASET WITH HELP OF PANDAS MODULE***

In [ ]:
import os; df = pd.read_excel('../data/perovskites.xlsx' if os.path.exists('../data/perovskites.xlsx') else ('data/perovskites.xlsx' if os.path.exists('data/perovskites.xlsx') else 'https://raw.githubusercontent.com/Adhavan1801/PerovskiteML/main/data/perovskites.xlsx'))

In [ ]:
df

         formula  target
0      ReBTeGeO6  380.39
1      GeZnAl2O6  372.33
2     TcCaMnBeO6  359.72
3     ReSeAlCeO6  355.14
4     OsSeAlCeO6  352.48
..           ...     ...
583   Au2SeTeBr6   24.82
584  HgOsTeAgBr6   24.24
585  HgIrTeAgBr6   24.20
586  HgPtTeAgBr6   24.13
587  HgAuTeAgBr6   24.09

[587 rows x 2 columns]

**GENERATING FEATURES WITH CBFV(Magpie)**

In [ ]:
X, y, formulas, skipped = generate_features(
    df,
    elem_prop='magpie',  # Choose a featurization scheme (e.g., 'oliynyk', 'magpie')
    drop_duplicates=True,  # Keep duplicates if any
    extend_features=True,  # Extend features or not
    sum_feat=True
   )

/usr/local/lib/python3.11/dist-packages/CBFV/composition.py:217: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df['formula'].value_counts()[0] > 1:

Duplicate formula(e) removed using default pandas function

Processing Input Data: 100%|██████████| 587/587 [00:00<00:00, 24858.96it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 587/587 [00:00<00:00, 10793.81it/s]

	Creating Pandas Objects...

In [ ]:
X

,sum_Number,sum_MendeleevNumber,sum_AtomicWeight,sum_MeltingT,sum_Column,sum_Row,sum_CovalentRadius,sum_Electronegativity,sum_NsValence,sum_NpValence,...,mode_NValence,mode_NsUnfilled,mode_NpUnfilled,mode_NdUnfilled,mode_NfUnfilled,mode_NUnfilled,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber
0,212.00,817.00,493.25,8069.86,146.00,29.00,889.00,28.69,20.00,31.00,...,6.00,0.00,2.00,0.00,0.00,2.00,9.11,0.00,0.00,12.00
1,136.00,816.00,287.98,4099.82,148.00,26.00,880.00,27.52,20.00,28.00,...,6.00,0.00,2.00,0.00,0.00,2.00,9.11,0.00,0.00,12.00
2,140.00,701.00,298.02,6952.80,114.00,27.00,954.00,26.66,20.00,24.00,...,6.00,0.00,2.00,0.00,0.00,2.00,9.11,0.00,0.00,12.00
3,228.00,753.00,528.26,6286.27,135.00,31.00,992.00,27.82,20.00,29.00,...,6.00,0.00,2.00,0.00,0.00,2.00,9.11,0.00,0.00,12.00
4,229.00,756.00,532.28,6133.27,136.00,31.00,985.00,28.12,20.00,29.00,...,6.00,0.00,2.00,0.00,0.00,2.00,9.11,0.00,0.00,12.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582,454.00,881.00,1079.92,5486.12,156.00,45.00,1250.00,27.49,18.00,38.00,...,17.00,0.00,1.00,0.00,0.00,1.00,29.48,1.46,0.00,64.00
583,465.00,853.00,1105.71,7092.71,149.00,46.00,1279.00,25.99,19.00,34.00,...,17.00,0.00,1.00,0.00,0.00,1.00,29.48,1.46,0.00,64.00
584,466.00,856.00,1107.70,6525.71,150.00,46.00,1276.00,25.99,19.00,34.00,...,17.00,0.00,1.00,0.00,0.00,1.00,29.48,1.46,0.00,64.00
585,467.00,859.00,1110.57,5828.11,151.00,46.00,1271.00,26.07,18.00,34.00,...,17.00,0.00,1.00,0.00,0.00,1.00,29.48,1.46,0.00,64.00
586,468.00,862.00,1112.45,5124.04,152.00,46.00,1271.00,26.33,18.00,34.00,...,17.00,0.00,1.00,0.00,0.00,1.00,29.48,1.46,0.00,64.00

In [ ]:
y

0     380.39
1     372.33
2     359.72
3     355.14
4     352.48
       ...
582    24.82
583    24.24
584    24.20
585    24.13
586    24.09
Name: target, Length: 587, dtype: float64

In [ ]:
formulas

0        ReBTeGeO6
1        GeZnAl2O6
2       TcCaMnBeO6
3       ReSeAlCeO6
4       OsSeAlCeO6
          ...
582     Au2SeTeBr6
583    HgOsTeAgBr6
584    HgIrTeAgBr6
585    HgPtTeAgBr6
586    HgAuTeAgBr6
Name: formula, Length: 587, dtype: object

In [ ]:
skipped

[]

**COUNTING THE FEATURES GIVEN BY CBFV(Magpie)**

In [ ]:
count=0
for feature in X.columns:
    count+=1
print("Total number of features extracted :",count)

Total number of features extracted : 154

#**FINDING THE COMPOSITION OF THE FORMULAS WITH HELP OF PYMATGEN**

In [ ]:
comp = [formula for formula in df['formula']]

#**FINDING GEOMENTRIC FACTORS WHICH ARE NOT IN CBFV**

In [ ]:
def featurize_pymatgen(formula):
  try:
        comp = Composition(formula)
        elements = list(comp.elements)
        print(elements)
        # Mean properties
        mean_electronegativity = np.mean([el.X for el in elements if el.X is not None])
        mean_ionic_radii = np.mean([max(el.ionic_radii.values(), default=0) for el in elements])
        num_elements = len(elements)

        if elements:
            # Indented block for the 'if' statement
            # Define A, B, and X site candidates
            a_elements = [el for el in elements if el.is_alkali or el.is_alkaline or el.is_lanthanoid]
            b_elements = [el for el in elements if el.is_transition_metal]
            x_site = next((el for el in elements if el.is_chalcogen or el.is_halogen), None)
            print(a_elements)
            #print(b_elements)
            #print(x_site)

            tolerance_factor, octahedral_factor, rho_A, rho_B = None, None, None, None

            # Case 1: A₂BB'X₆ (e.g., 2 A, 2 distinct B, 6 X)
            if len(a_elements) == 1 and len(b_elements) == 2 and x_site and comp.get_el_amt_dict()[x_site.symbol] == 6:
                a_site = a_elements[0]
                b_site, b_prime_site = b_elements[0], b_elements[1]
                r_A = max(a_site.ionic_radii.values(), default=0)
                r_B = max(b_site.ionic_radii.values(), default=0)
                r_B_prime = max(b_prime_site.ionic_radii.values(), default=0)
                r_X = max(x_site.ionic_radii.values(), default=0)

                if r_A > 0 and r_B > 0 and r_B_prime > 0 and r_X > 0:
                    avg_r_B = (r_B + r_B_prime) / 2
                    tolerance_factor = (r_A + r_X) / (np.sqrt(2) * (avg_r_B + r_X))
                    octahedral_factor = avg_r_B / r_X
                    rho_A = (r_A - r_X) / (2 * r_X)
                    rho_B = (r_A - avg_r_B) / (2 * r_X)

            # Case 2: AA'B₂X₆ (e.g., 2 distinct A, 1 B type, 6 X)
            elif len(a_elements) == 2 and len(b_elements) == 1 and x_site and comp.get_el_amt_dict()[x_site.symbol] == 6:
                a_site, a_prime_site = a_elements[0], a_elements[1]
                b_site = b_elements[0]
                r_A = max(a_site.ionic_radii.values(), default=0)

                r_A_prime = max(a_prime_site.ionic_radii.values(), default=0)

                r_B = max(b_site.ionic_radii.values(), default=0)
                r_X = max(x_site.ionic_radii.values(), default=0)

                if r_A > 0 and r_A_prime > 0 and r_B > 0 and r_X > 0:
                    avg_r_A = (r_A + r_A_prime) / 2
                    tolerance_factor = (avg_r_A + r_X) / (np.sqrt(2) * (r_B + r_X))
                    octahedral_factor = r_B / r_X
                    rho_A = (avg_r_A - r_X) / (2 * r_X)
                    rho_B = (avg_r_A - r_B) / (2 * r_X)

            # Case 3: AA'BB'X₆ (e.g., 2 distinct A, 2 distinct B, 6 X)
            elif len(a_elements) == 2 and len(b_elements) == 2 and x_site and comp.get_el_amt_dict()[x_site.symbol] == 6:
                a_site, a_prime_site = a_elements[0], a_elements[1]
                b_site, b_prime_site = b_elements[0], b_elements[1]
                r_A = max(a_site.ionic_radii.values(), default=0)
                r_A_prime = max(a_prime_site.ionic_radii.values(), default=0)
                r_B = max(b_site.ionic_radii.values(), default=0)
                r_B_prime = max(b_prime_site.ionic_radii.values(), default=0)
                r_X = max(x_site.ionic_radii.values(), default=0)

                if r_A > 0 and r_A_prime > 0 and r_B > 0 and r_B_prime > 0 and r_X > 0:
                    avg_r_A = (r_A + r_A_prime) / 2
                    avg_r_B = (r_B + r_B_prime) / 2
                    tolerance_factor = (avg_r_A + r_X) / (np.sqrt(2) * (avg_r_B + r_X))
                    octahedral_factor = avg_r_B / r_X
                    rho_A = (avg_r_A - r_X) / (2 * r_X)
                    rho_B = (avg_r_A - avg_r_B) / (2 * r_X)

        # Return results
        return {

            "mean_electronegativity": mean_electronegativity,
            "mean_ionic_radii": mean_ionic_radii,
            "num_elements": num_elements,
            "tolerance_factor": tolerance_factor,
            "octahedral_factor": octahedral_factor,
            "mismatch_factor_A": rho_A,
            "mismatch_factor_B": rho_B
        }

  except Exception as e:
        print(f"Error featurizing {formula}: {e}")
        return {

            "mean_electronegativity": None,
            "mean_ionic_radii": None,
            "num_elements": None,
            "tolerance_factor": None,
            "octahedral_factor": None,
            "mismatch_factor_A": None,
            "mismatch_factor_B": None
        }

In [ ]:

mean_electronegativity=[]
mean_ionic_radii=[]
tolerance_factor_d=[]
octahedral_factor=[]
mismatch_factor_A=[]
mismatch_factor_B=[]
print(formulas[0])
print(featurize_pymatgen(formulas[0]))
#for i in range(len(formulas)):
 # features=featurize_pymatgen(formulas[i])

  #mean_electronegativity.append(features['mean_electronegativity'])
  #mean_ionic_radii.append(features['mean_ionic_radii'])
  #tolerance_factor_d.append(features['tolerance_factor'])
  #octahedral_factor.append(features['octahedral_factor'])
  #mismatch_factor_A.append(features['mismatch_factor_A'])
  #mismatch_factor_B.append(features['mismatch_factor_B'])

ReBTeGeO6
[Element Re, Element B, Element Te, Element Ge, Element O]
[]
{'mean_electronegativity': 2.298, 'mean_ionic_radii': 1.076, 'num_elements': 5, 'tolerance_factor': None, 'octahedral_factor': None, 'mismatch_factor_A': None, 'mismatch_factor_B': None}

In [ ]:
extra_features=pd.DataFrame( {

            "mean_electronegativity": mean_electronegativity,
            "mean_ionic_radii": mean_ionic_radii,
            "tolerance_factor": tolerance_factor_d,
            "octahedral_factor": octahedral_factor,
            "mismatch_factor_A": mismatch_factor_A,
            "mismatch_factor_B": mismatch_factor_B
        })

In [ ]:
extra_features

Empty DataFrame
Columns: [mean_electronegativity, mean_ionic_radii, tolerance_factor, octahedral_factor, mismatch_factor_A, mismatch_factor_B]
Index: []

In [ ]:
x=pd.concat([X,extra_features],axis=1)

In [ ]:
x

,sum_Number,sum_MendeleevNumber,sum_AtomicWeight,sum_MeltingT,sum_Column,sum_Row,sum_CovalentRadius,sum_Electronegativity,sum_NsValence,sum_NpValence,...,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber,mean_electronegativity,mean_ionic_radii,tolerance_factor,octahedral_factor,mismatch_factor_A,mismatch_factor_B
0,212.00,817.00,493.25,8069.86,146.00,29.00,889.00,28.69,20.00,31.00,...,9.11,0.00,0.00,12.00,NaN,NaN,NaN,NaN,NaN,NaN
1,136.00,816.00,287.98,4099.82,148.00,26.00,880.00,27.52,20.00,28.00,...,9.11,0.00,0.00,12.00,NaN,NaN,NaN,NaN,NaN,NaN
2,140.00,701.00,298.02,6952.80,114.00,27.00,954.00,26.66,20.00,24.00,...,9.11,0.00,0.00,12.00,NaN,NaN,NaN,NaN,NaN,NaN
3,228.00,753.00,528.26,6286.27,135.00,31.00,992.00,27.82,20.00,29.00,...,9.11,0.00,0.00,12.00,NaN,NaN,NaN,NaN,NaN,NaN
4,229.00,756.00,532.28,6133.27,136.00,31.00,985.00,28.12,20.00,29.00,...,9.11,0.00,0.00,12.00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582,454.00,881.00,1079.92,5486.12,156.00,45.00,1250.00,27.49,18.00,38.00,...,29.48,1.46,0.00,64.00,NaN,NaN,NaN,NaN,NaN,NaN
583,465.00,853.00,1105.71,7092.71,149.00,46.00,1279.00,25.99,19.00,34.00,...,29.48,1.46,0.00,64.00,NaN,NaN,NaN,NaN,NaN,NaN
584,466.00,856.00,1107.70,6525.71,150.00,46.00,1276.00,25.99,19.00,34.00,...,29.48,1.46,0.00,64.00,NaN,NaN,NaN,NaN,NaN,NaN
585,467.00,859.00,1110.57,5828.11,151.00,46.00,1271.00,26.07,18.00,34.00,...,29.48,1.46,0.00,64.00,NaN,NaN,NaN,NaN,NaN,NaN
586,468.00,862.00,1112.45,5124.04,152.00,46.00,1271.00,26.33,18.00,34.00,...,29.48,1.46,0.00,64.00,NaN,NaN,NaN,NaN,NaN,NaN

#**IMPORTING MODULES FOR PREDICTION**

In [ ]:
!pip install lazypredict
from sklearn.feature_selection import RFE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from lazypredict.Supervised import LazyRegressor

Collecting lazypredict
  Downloading lazypredict-0.2.16-py2.py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from lazypredict) (8.1.8)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from lazypredict) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from lazypredict) (2.2.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from lazypredict) (4.67.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from lazypredict) (1.4.2)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.11/dist-packages (from lazypredict) (4.5.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.11/dist-packages (from lazypredict) (2.1.4)
Collecting pytest-runner (from lazypredict)
  Downloading pytest_runner-6.0.1-py3-none-any.whl.metadata (7.3 kB)
Collecting mlflow>=2.0.0 (from lazypredict)
  Downloading mlflow-2.21.3-py3-none-any.whl.metadata (30 kB)
Collecting mlflow-skinny==2.21.3 (from mlflow>=2.0.0->lazypredict)
  Downloading mlflow_skinny-2.21.3-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.0.0->lazypredict) (3.1.0)
Requirement already satisfied: Jinja2<4,>=2.11 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.0.0->lazypredict) (3.1.6)
Collecting alembic!=1.10.0,<2 (from mlflow>=2.0.0->lazypredict)
  Downloading alembic-1.15.2-py3-none-any.whl.metadata (7.3 kB)
Collecting docker<8,>=4.0.0 (from mlflow>=2.0.0->lazypredict)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow>=2.0.0->lazypredict)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<24 (from mlflow>=2.0.0->lazypredict)
  Downloading gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: markdown<4,>=3.3 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.0.0->lazypredict) (3.7)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.0.0->lazypredict) (3.10.1)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.0.0->lazypredict) (1.26.4)
Requirement already satisfied: pyarrow<20,>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.0.0->lazypredict) (18.1.0)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.0.0->lazypredict) (1.15.2)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from mlflow>=2.0.0->lazypredict) (2.0.40)
Requirement already satisfied: cachetools<6,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (5.5.2)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (3.1.1)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict)
  Downloading databricks_sdk-0.50.0-py3-none-any.whl.metadata (38 kB)
Collecting fastapi<1 (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict)
  Downloading fastapi-0.115.12-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (3.1.44)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (8.6.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (1.31.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (1.31.1)
Requirement already satisfied: packaging<25 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (24.2)
Requirement already satisfied: protobuf<6,>=3.12.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (5.29.4)
Requirement already satisfied: pydantic<3,>=1.10.8 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (2.11.3)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (2.32.3)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (0.5.3)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (4.13.2)
Collecting uvicorn<1 (from mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict)
  Downloading uvicorn-0.34.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->lazypredict) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->lazypredict) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->lazypredict) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->lazypredict) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost->lazypredict) (2.21.5)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow>=2.0.0->lazypredict) (1.1.3)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from docker<8,>=4.0.0->mlflow>=2.0.0->lazypredict) (2.4.0)
Requirement already satisfied: Werkzeug>=3.1 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow>=2.0.0->lazypredict) (3.1.3)
Requirement already satisfied: itsdangerous>=2.2 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow>=2.0.0->lazypredict) (2.2.0)
Requirement already satisfied: blinker>=1.9 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow>=2.0.0->lazypredict) (1.9.0)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow>=2.0.0->lazypredict)
  Downloading graphql_core-3.2.6-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow>=2.0.0->lazypredict)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2<4,>=2.11->mlflow>=2.0.0->lazypredict) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow>=2.0.0->lazypredict) (3.2.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->lazypredict) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.0.0->lazypredict) (3.1.1)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.11/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (2.38.0)
Collecting starlette<0.47.0,>=0.40.0 (from fastapi<1->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict)
  Downloading starlette-0.46.2-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (3.21.0)
Requirement already satisfied: deprecated>=1.2.6 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (1.2.18)
Requirement already satisfied: opentelemetry-semantic-conventions==0.52b1 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (0.52b1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.10.8->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.10.8->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.10.8->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (2025.1.31)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/dist-packages (from uvicorn<1->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (0.14.0)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.11/dist-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (1.17.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (5.0.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (4.9)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.11/dist-packages (from starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (4.9.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (1.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.21.3->mlflow>=2.0.0->lazypredict) (0.6.1)
Downloading lazypredict-0.2.16-py2.py3-none-any.whl (14 kB)
Downloading mlflow-2.21.3-py3-none-any.whl (28.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.2/28.2 MB 69.2 MB/s eta 0:00:00
Downloading mlflow_skinny-2.21.3-py3-none-any.whl (6.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 119.4 MB/s eta 0:00:00
Downloading pytest_runner-6.0.1-py3-none-any.whl (7.2 kB)
Downloading alembic-1.15.2-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.9/231.9 kB 21.8 MB/s eta 0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 13.8 MB/s eta 0:00:00
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 12.0 MB/s eta 0:00:00
Downloading gunicorn-23.0.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 7.9 MB/s eta 0:00:00
Downloading databricks_sdk-0.50.0-py3-none-any.whl (692 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 692.3/692.3 kB 52.7 MB/s eta 0:00:00
Downloading fastapi-0.115.12-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 9.2 MB/s eta 0:00:00
Downloading graphql_core-3.2.6-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.4/203.4 kB 19.0 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading uvicorn-0.34.1-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 6.2 MB/s eta 0:00:00
Downloading starlette-0.46.2-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 7.6 MB/s eta 0:00:00
Installing collected packages: uvicorn, pytest-runner, gunicorn, graphql-core, starlette, graphql-relay, docker, alembic, graphene, fastapi, databricks-sdk, mlflow-skinny, mlflow, lazypredict
Successfully installed alembic-1.15.2 databricks-sdk-0.50.0 docker-7.1.0 fastapi-0.115.12 graphene-3.4.3 graphql-core-3.2.6 graphql-relay-3.2.0 gunicorn-23.0.0 lazypredict-0.2.16 mlflow-2.21.3 mlflow-skinny-2.21.3 pytest-runner-6.0.1 starlette-0.46.2 uvicorn-0.34.1

# **SCALING THE DATASET**

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)
X_scaled = pd.DataFrame(X_scaled, columns=x.columns)

In [ ]:

X_scaled

,sum_Number,sum_MendeleevNumber,sum_AtomicWeight,sum_MeltingT,sum_Column,sum_Row,sum_CovalentRadius,sum_Electronegativity,sum_NsValence,sum_NpValence,...,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber,mean_electronegativity,mean_ionic_radii,tolerance_factor,octahedral_factor,mismatch_factor_A,mismatch_factor_B
0,-0.89,0.03,-0.82,1.18,0.27,-1.19,-1.37,0.96,0.73,-0.63,...,-1.08,-1.09,0.00,-1.11,NaN,NaN,NaN,NaN,NaN,NaN
1,-1.80,0.01,-1.83,-1.44,0.50,-1.71,-1.43,0.27,0.73,-1.42,...,-1.08,-1.09,0.00,-1.11,NaN,NaN,NaN,NaN,NaN,NaN
2,-1.76,-2.52,-1.78,0.44,-3.30,-1.53,-0.96,-0.23,0.73,-2.48,...,-1.08,-1.09,0.00,-1.11,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.70,-1.37,-0.64,0.00,-0.96,-0.84,-0.72,0.45,0.73,-1.15,...,-1.08,-1.09,0.00,-1.11,NaN,NaN,NaN,NaN,NaN,NaN
4,-0.69,-1.31,-0.62,-0.10,-0.84,-0.84,-0.77,0.62,0.73,-1.15,...,-1.08,-1.09,0.00,-1.11,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
582,2.01,1.43,2.08,-0.52,1.39,1.58,0.89,0.25,-1.68,1.22,...,1.09,0.36,0.00,0.91,NaN,NaN,NaN,NaN,NaN,NaN
583,2.14,0.82,2.21,0.54,0.61,1.75,1.08,-0.63,-0.47,0.17,...,1.09,0.36,0.00,0.91,NaN,NaN,NaN,NaN,NaN,NaN
584,2.16,0.89,2.22,0.16,0.72,1.75,1.06,-0.63,-0.47,0.17,...,1.09,0.36,0.00,0.91,NaN,NaN,NaN,NaN,NaN,NaN
585,2.17,0.95,2.23,-0.30,0.83,1.75,1.03,-0.58,-1.68,0.17,...,1.09,0.36,0.00,0.91,NaN,NaN,NaN,NaN,NaN,NaN
586,2.18,1.02,2.24,-0.76,0.94,1.75,1.03,-0.43,-1.68,0.17,...,1.09,0.36,0.00,0.91,NaN,NaN,NaN,NaN,NaN,NaN

#**SPLITING THE DATASET FOR TRAIN AND TEST**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
reg = LazyRegressor(verbose=0, ignore_warnings=True, random_state=42)
models, predictions = reg.fit(X_train, X_test, y_train, y_test)

  0%|          | 0/42 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000612 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5708
[LightGBM] [Info] Number of data points in the train set: 469, number of used features: 138
[LightGBM] [Info] Start training from score 111.309147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [ ]:
models

,Adjusted R-Squared,R-Squared,RMSE,Time Taken
Model,,,,
Lars,7661543343974297310763585665175125162912120832.00,-2815780887101664877787069955074165722125959168.00,3232059917559073425326080.00,0.22
KernelRidge,10.50,-2.49,113.83,0.10
GaussianProcessRegressor,9.59,-2.16,108.22,0.28
RANSACRegressor,9.53,-2.14,107.86,1.12
QuantileRegressor,3.88,-0.06,62.68,1.49
DummyRegressor,3.72,-0.00,60.91,0.02
LarsCV,3.65,0.03,60.14,0.91
NuSVR,3.06,0.24,52.97,0.05
SVR,3.05,0.25,52.86,0.06
LinearSVR,2.72,0.37,48.47,0.13
PassiveAggressiveRegressor,2.44,0.47,44.24,0.04
OrthogonalMatchingPursuit,2.36,0.50,43.07,0.02
OrthogonalMatchingPursuitCV,2.31,0.52,42.21,0.03
TransformedTargetRegressor,2.29,0.53,41.87,0.03
LinearRegression,2.29,0.53,41.87,0.22
GammaRegressor,2.28,0.53,41.77,0.10
LassoLarsCV,2.26,0.54,41.45,0.38
LassoLars,2.25,0.54,41.35,0.11
LassoLarsIC,2.25,0.54,41.35,1.46
SGDRegressor,2.25,0.54,41.28,0.03
PoissonRegressor,2.24,0.54,41.20,0.21
Lasso,2.24,0.54,41.17,0.08
TweedieRegressor,2.24,0.54,41.14,0.13
HuberRegressor,2.22,0.55,40.83,1.49
ElasticNet,2.22,0.55,40.82,0.07
RidgeCV,2.20,0.56,40.52,0.04
LassoCV,2.19,0.56,40.27,7.77
MLPRegressor,2.19,0.56,40.27,2.15
BayesianRidge,2.18,0.57,40.17,0.10
ElasticNetCV,2.18,0.57,40.15,7.05
Ridge,2.17,0.57,40.01,0.02
KNeighborsRegressor,2.12,0.59,39.14,0.08
ExtraTreeRegressor,2.07,0.61,38.17,0.07
AdaBoostRegressor,1.96,0.65,36.13,0.80
XGBRegressor,1.84,0.69,33.75,0.85
HistGradientBoostingRegressor,1.74,0.73,31.86,2.18
LGBMRegressor,1.73,0.73,31.63,0.23
GradientBoostingRegressor,1.71,0.74,31.19,2.50
DecisionTreeRegressor,1.71,0.74,31.10,0.14
ExtraTreesRegressor,1.70,0.74,30.96,3.88
RandomForestRegressor,1.70,0.74,30.84,1.98
BaggingRegressor,1.61,0.78,28.80,0.34